//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCStok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Musteriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Musteriler()
        {
            this.Satislar = new HashSet<Satislar>();
        }
    
        public int Id { get; set; }
        [StringLength(maximumLength:50,MinimumLength =3,ErrorMessage ="Bu Alan 3 karakterden kýsa ve 50 karakterden uzun olamaz")]
        [Required(ErrorMessage ="Zorunlu Alan")]
        public string Ad { get; set; }
        [StringLength(maximumLength: 50, MinimumLength = 3, ErrorMessage = "Bu Alan 3 karakterden kýsa ve 50 karakterden uzun olamaz")]
        [Required(ErrorMessage = "Zorunlu Alan")]
        public string Soyad { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satislar> Satislar { get; set; }
    }
}
