//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvEntityProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenelBilgiler
    {
        public int Id { get; set; }
        public Nullable<int> BilgilerId { get; set; }
        public string Egitim { get; set; }
        public string IsDeneyimleri { get; set; }
    
        public virtual Bilgiler Bilgiler { get; set; }
    }
}
