//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ders_31_Entity_Framework_Listeleme
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Personel
    {
        public byte Perid { get; set; }
        public string PerAd { get; set; }
        public string PerSoyad { get; set; }
        public string PerSehir { get; set; }
        public Nullable<short> PerMaas { get; set; }
        public Nullable<bool> PerDurum { get; set; }
        public string PerYas { get; set; }
    }
}
