//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Hakkimizdas
{
    public int Id { get; set; }
    public string Metin { get; set; }
}

public partial class Kategoriler
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Kategoriler()
    {
        this.Tarifler = new HashSet<Tarifler>();
    }

    public int Id { get; set; }
    public string Ad { get; set; }
    public string Resim { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Tarifler> Tarifler { get; set; }
}

public partial class Kullanicilar
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Kullanicilar()
    {
        this.Tarifler = new HashSet<Tarifler>();
        this.Yorumlar = new HashSet<Yorumlar>();
    }

    public int Id { get; set; }
    public string Ad_Soyad { get; set; }
    public string Email { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Tarifler> Tarifler { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Yorumlar> Yorumlar { get; set; }
}

public partial class Mesajlar
{
    public int Id { get; set; }
    public string Baslik { get; set; }
    public string Mail { get; set; }
    public string Icerik { get; set; }
    public string Gonderen { get; set; }
}

public partial class Tarifler
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Tarifler()
    {
        this.Yemeklers = new HashSet<Yemekler>();
    }

    public int Id { get; set; }
    public Nullable<int> KullaniciId { get; set; }
    public Nullable<int> KategoriId { get; set; }
    public string Ad { get; set; }
    public string Malzeme { get; set; }
    public string Tarif { get; set; }
    public string Resim { get; set; }
    public Nullable<System.DateTime> Tarih { get; set; }
    public Nullable<bool> Durum { get; set; }

    public virtual Kategoriler Kategoriler { get; set; }
    public virtual Kullanicilar Kullanicilar { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Yemekler> Yemeklers { get; set; }
}

public partial class Yemekler
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Yemekler()
    {
        this.Yorumlars = new HashSet<Yorumlar>();
        this.Yorumlars1 = new HashSet<Yorumlar>();
    }

    public int Id { get; set; }
    public Nullable<int> TarifId { get; set; }
    public Nullable<double> Puan { get; set; }
    public Nullable<bool> GununYemegi { get; set; }

    public virtual Tarifler Tarifler { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Yorumlar> Yorumlars { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Yorumlar> Yorumlars1 { get; set; }
}

public partial class Yorumlar
{
    public int Id { get; set; }
    public Nullable<int> KullaniciId { get; set; }
    public Nullable<int> YemekId { get; set; }
    public Nullable<System.DateTime> Tarih { get; set; }
    public Nullable<bool> OnayDurum { get; set; }
    public string Icerik { get; set; }

    public virtual Kullanicilar Kullanicilar { get; set; }
    public virtual Yemekler Yemekler { get; set; }
    public virtual Yemekler Yemekler1 { get; set; }
}
