//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace is_takip_proje.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firmalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Firmalar()
        {
            this.Cagrilar = new HashSet<Cagrilar>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SehirId { get; set; }
        public Nullable<int> IlceId { get; set; }
        public Nullable<int> SektorId { get; set; }
        public string FirmaAdi { get; set; }
        public string Yetkili { get; set; }
        public string Telefon { get; set; }
        public string Mail { get; set; }
        public string Adres { get; set; }
    
        public virtual Ilceler Ilceler { get; set; }
        public virtual Sehirler Sehirler { get; set; }
        public virtual Sektorler Sektorler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cagrilar> Cagrilar { get; set; }
    }
}
