//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace is_takip_proje.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gorevler
    {
        public int Id { get; set; }
        public Nullable<int> GorevAlanId { get; set; }
        public Nullable<int> GorevVerenId { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual Personeller Personeller { get; set; }
        public virtual Personeller Personeller1 { get; set; }
    }
}
