using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.IO;
using System.Linq;
using System.Runtime.ConstrainedExecution;
using System.Security.Cryptography;
using System.Security.Policy;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Windows.Forms;
using static System.Net.WebRequestMethods;
using static System.Windows.Forms.VisualStyles.VisualStyleElement;
using static System.Windows.Forms.VisualStyles.VisualStyleElement.ListView;
using static System.Windows.Forms.VisualStyles.VisualStyleElement.Rebar;

namespace Minİstanbul
{
    public partial class FrmMuzeler : Form
    {
        public FrmMuzeler()
        {
            InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            FrmAnasayfa frmAnasayfa = new FrmAnasayfa();
            frmAnasayfa.Show();
            this.Hide();
        }

       

        private void comboBox1_SelectedIndexChanged(object sender, EventArgs e)
        {
            if (comboBox1.Text == "Yerebatan Sarnıcı")
            {
                richTextBox1.Text = "532 senesinde Bizans İmparatoru I. Justinianus tarafından inşa ettirilen Yerebatan Sarnıcı’nın yapım amacı ise sarayın ve bölgede yaşayan insanların su ihtiyacını karşılamasıydı.Fatih Sultan Mehmet’in İstanbul’u işgal etmesiyle birlikte bir süre daha kullanılan sarnıç bu sefer de Topkapı Sarayı‘nın su ihtiyacını karşılamış.Osmanlı döneminde durgun suyun temiz olmadığı düşünüldüğü tesisler kurulmuş ve sarnıç bir daha kullanılmamış.9 bin 800 metrekarelik alan üzerine inşa edilen sarnıca gitmek için 52 basamaklı bir merdivenden iniliyor.Çoğu silindir şeklinde olan 336 adet sütunun başlıkları ise farklı özelliklere sahip.Bazıları Corinth üslubunu yansıtırken, bazıları da Doric üslubunu yansıtıyor.MüzeKart’ın geçerli olmadığı Yerebatan Sarnıcı’na giriş ücreti yetişkinler için 15 TL, öğrenciler için 5 TL, yabancı uyruklular içinse 30 TL’dir.Sarnıca girişte MüzeKart geçerli değil.Sarnıç haftanın 7 günü saat 09:00 ile 17:30 arasında ziyarete açık olduğu gibi dini bayramların ilk gününde de 12:00 ile 13:00 arasında ziyaret edilebiliyor.Fatih ilçesinde, Sultanahmet semtinde konumlanan Yerebatan Sarnıcı’na gitmek isteyenler, Sultanahmet istikametinde hareket eden herhangi bir otobüse binebilecekleri gibi, Kapalı Çarşı’ya kadar otobüsle gelip, buradan da 10 – 15 dakika yürüyerek sarnıca ulaşabilirler.Kabataş – Zeytinburnu hattında çalışan tramvaylardan herhangi bir tanesine binerek de Yerebatan Sarnıcı’na kolaylıkla gelinebilir.140 metre uzunluğunda ev 70 metre genişliğinde olan Yerebatan Sarnıcı’nın 100 bin ton su tutma kapasitesi bulunuyor.";
                pictureBox2.ImageLocation = @"C:\Users\musau\Desktop\Murat Yücedağ\C#\52.Ders\resimler\yerebatan.jpg";
            }
            if (comboBox1.Text == "Aya İrini Müzesi")
            {
                richTextBox1.Text = "4. yüzyılın başlarında inşa edilen Aya İrini, camiye çevrilemeyen en büyük Bizans Kilisesi olarak biliniyor.Kilisenin, İstanbul’un fethinden sonra camiye çevrilmemesinin sebebi olarak Topkapı Sarayı‘nı çevreleyen Sur - ı Sultan‘ın içinde kalması gösteriliyor.Roma zamanından kalma Artemis, Apollon ve Afrodit yapılarının kalıntılarıyla yapıldığı söylenir. 700‘lü ve 800‘lü yıllarda bölgede yaşanan şiddetli depremler sebebiyle Aya İrini büyük hasar almış.Salı günleri hariç haftanın her günü ziyarete açık olan Aya İrini Müzesi’ne kışın (3 Ekim – 14 Nisan) saat 09.00 ile 19.00 arasında, yazın ( 15 Nisan – 2 Ekim) ise saat 09:00 ile 19:00 arasında gidebilirsiniz. Yalnız kışın bilet satışı saat 16:00’da bitiyor.MüzeKart’ın geçerli olmadığı müzeye giriş ücreti ise 60 TL’dir.Fatih ilçesinde konumlanan Aya irini Müzesi’ne gitmek için Bağcılar, Kabataş ve Zeytinburnu hattında çalışan tramvaylardan herhangi bir tanesine binebilirsiniz.";
                pictureBox2.ImageLocation = @"C:\Users\musau\Desktop\Murat Yücedağ\C#\52.Ders\resimler\ayairini.jpg";
            }
            if (comboBox1.Text == "Sakıp Sabancı Müzesi")
            {
                richTextBox1.Text = "Sakıp Sabancı’nın 1933 ile 2004 seneleri arasında tek başına yaratmaya başladığı hat, güzel yazı, el yazması Kuran-ı Kerim ve çok değerli kitap koleksiyonları gün geçtikçe büyüdü ve yurt dışındaki müzelerden dahi ilgi görmeye başladı.Zaman zaman müzelerde de sergilenen bu nadide koleksiyonun Türk Milleti’ne daha yararlı olabilmesi adına kendi aslarına kurulan bir müzede sergilenmesinin daha doğru olacağını düşünerek Sabancı Ailesi, Emirgan’da yer alan Atlı Köşk’ü 1998 yılında Sabancı Üniversitesi’ne tahsis etti. 4 yıl içerisinde de Sakıp Sabancı Müzesi, ziyaretçilerine kapılarını açtı.Yıllar içerisinde büyümeye ve gelişmeye devam eden koleksiyonun sergilendiği müzede ayrıca pek çok etkinlik, toplantı, seminer, sempozyum ve kısa süreli sergiler düzenleniyor.Günümüzde de halen aktif olarak hizmet veren müze ayrıca, çocuklar ve yetişkinler için eğitim programları hazırlıyor.Konumu, müzecilik anlayışı ve eserleri ile Sakıp Sabancı Müzesi, son yıllarda hizmete açılmış Türkiye’nin en önemli müzeleri arasında yer alıyor.Pazartesi günleri, 1 Ocak, Ramazan ve Kurban bayramlarının ilk günü haricinde ziyaretçilere kapısı açık olan Sakıp Sabancı Müzesi’ne çarşamba günleri saat 10:00 ile 20:00 arasında, haftanın diğer günleri ise saat 10:00 ile 18:00 arasında gidebilirsiniz.Çarşamba günleri girişlerin ücretsiz olduğu müzeye diğer günler için tam bilet 50 TL, öğrenciler, öğretmenler, 65 yaş üzeri ziyaretçiler, Müzekart Plus sahiplerine ise 25 TL.SSM Dostu kart sahipleri, 14 yaş altı çocuklar ile bir refakatçi, Engelliler ve bir refakatçi,Sabancı Üniversitesi akademik ve idari personeli, ICOM kart sahipleri, Basın mensupları, MMKD kart sahipleri, The Cultivist kart sahipleri ve + 3 ziyaretçi, The Sotheby’s Preffered Card kart sahipleri ve +3 ziyaretçi, Larry’s List kart sahipleri +1 ziyaretçi için ise girişler ücretsiz.Emirgan Korusu’nun hemen altında konumlanan Sakıp Sabancı Müzesi’ne gitmek için Dentur firmasının Kabataş’tan kalkan vapurlarıyla Milli Saraylar Uğramalı Boğaz Turu kapsamında Emirgan’a kadar gelebilirsiniz.Tur şirketi ile müze arasında yapılan anlaşma sebebiyle müzeye, 15 TL ödeyerek girebilirsiniz.Müzeye otobüsle gelmek isteyenlerse, Beşiktaş – Sarıyer hattından geçen herhangi bir otobüse binerek Emirgan-Çınaraltı Durağı’nda inebilirler.";
                pictureBox2.ImageLocation = @"C:\Users\musau\Desktop\Murat Yücedağ\C#\52.Ders\resimler\sabanci.jpg";
            }
            if (comboBox1.Text == "İstanbul Oyuncak Müzesi")
            {
                richTextBox1.Text = "2005 senesinde Sunay Akın tarafından kurulan İstanbul Oyuncak Müzesi, alanında ilk olmuş ve diğer oyuncak müzelerinin açılmasına için de yol göstermiştir.1700’lü yıllardan günümüze kadar uzanan oyuncak kültürünün tarihine göz atabileceğiniz, çocuklardan ziyade yetişkinlere de hitap eden İstanbul Oyuncak Müzesi’nde aynı zamanda etkinlik ve organizasyon da düzenleniyor.Müze içerisinde yer alan ve masallardan fırlamış bir konseptle dizayn edilmiş kafede soluklanmak için oturabilir, bir şeyler içebilirsiniz.Ayrıca, rezervasyon yaptırarak kahvaltı yapabilir veya doğum günü organizasyonlarınızı burada gerçekleştirebilirsiniz.Tüm bunların dışında, çoğunlukla çocuklar için düzenlenen atölyelere katılım sağlayabilirsiniz.İstanbul’daki müzeler arasında özel bir yeri olan İstanbul Oyuncak Müzesi için bilet ücretleri tam 18 TL, indirimli ise 12 TL’dir.İndirimli biletlerden 3 – 12 yaş arası çocuklar, 65 yaş üstü vatandaşlar, öğretmenler, öğrenciler ve öğretim görevlileri faydalanabiliyor.Engellilere, 3 yaşın altındaki çocuklara, MMKD üyelerine, ICOM kart sahiplerine, basın kimlik kartı olanlara ve kokartlı rehberlere ise müzeye giriş ücretsiz.Pazartesi günleri hariç haftanın her günü ziyaretçilere kapılarını açan İstanbul Oyuncak Müzesi’ne hafta içi saat 09:30 ile 18:00 arasında, hafta sonu ise saat 09:30 ile 19:00 arasında gidebilirsiniz.Göztepe’de konumlanan müzeye gitmek için Kadıköy‘den hareket eden 10, 10B, 10S, 14Ç, 14 KS, 17, 17L, 19F, 19M, 19S, GZ1,GZ2, ER1, ER2 numaralı otobüslerden herhangi bir tanesine binip, Göztepe Durağı‘nda inebilirsiniz. Ayrıca, Kartal – Kadıköy Metrosu‘nu kullanarak Yenisahra Durağı‘na gelirseniz, kısa bir yürüyüşle müzeye ulaşabilirsiniz.";
                pictureBox2.ImageLocation = @"C:\Users\musau\Desktop\Murat Yücedağ\C#\52.Ders\resimler\oyuncak.jpg";
            }
            if (comboBox1.Text == "İstanbul Modern Sanat Müzesi")
            {
                richTextBox1.Text = "İstanbul’daki müzelerin bir tanesi de İstanbul Modern Sanat Müzesi. 2004 senesinde hizmete açılan ve Türkiye’nin özel girişimler aracılığıyla kurulan ilk modern sanat müzesi olma unvanını taşıyan İstanbul Modern Sanat Müzesi’nin arkasında aslında 20 seneye yakın bir çalışma yatıyor.8 bin metrekarelik alan üzerine inşa edilen müze, kurulduğundan bu yana binlerce yerli ve yabancı misafiri ağırladı.Müze içerisinde sergiler ve galerilerin yanı sıra sinema, kütüphane, restoran, ücretsiz eğitim programları, sosyal proje çalışmaları ve atölyeler yer alıyor.Haftanın her günü kapılarını ziyaretçilerine açan İstanbul Modern Sanat Müzesi için bilet fiyatları; tam 35 TL, 10 kişi ve üzeri gruplar 28 TL, indirimli ise 20 TL.Öğrenciler, öğretmenler ve 65 yaşın üzerindeki kişiler indirimli biletlerden faydalanabiliyor.12 yaşın altındaki çocuklar, ICOM VE CIMAM kart sahipleri ve engelliler içinse müzeye giriş ücretsiz.Ayrıca, Perşembe günleri ‘Sizin Perşembeniz’ sloganı altında müzeye ücretsiz giriş yapabiliyorsunuz. 18 - 25 yaşındaki gençler ise Salı günleri müzeye ücretsiz giriş yapabilir.Yıllın üyelik sisteminin de bulunduğu İstanbul Modern Sanat Müzesi için 75 TL’den başlayan yıllık üyelik yaptırdığınız takdirde, yıl boyunca müzeye ücretsiz giriş, misafir ziyaretçilere indirim, sergi açılışları için davetiye, sinema programlarına ücretsiz katılım gibi pek çok avantajdan faydalanabiliyorsunuz.1 Ocak’ta, Kurban ve Ramazan bayramlarının ilk günlerinde kapalı olan müzeyi Perşembe günleri saat 10:00 – 20:00 arasında, diğer günler ise saat 10:00 – 18:00 arasında ziyaret edebilirsiniz.Beyoğlu ilçesinde, Asmalımescit’te konumlanan İstanbul Modern Sanat Müzesi’ne gitmek için pek çok ulaşım alternatifi bulunuyor. Hacıosman - Taksim metrosu üzerindeki Şişhane durağında inerek yaklaşık 5 dakika bir yürüyüş sonucunda müzeye ulaşabilirsiniz; müze Pera Palace, Pera Müzesi ve Soho House İstanbul ile aynı cadde üzerinde bulunuyor.Anadolu yakasından seyahat edecekler ise Karaköy’e kadar vapurla gelip İstanbul Modern Sanat Müzesi’ne yürüyebilecekleri gibi, Karaköy - Beyoğlu tarihi füniküleri de kullanabilirsiniz";
                pictureBox2.ImageLocation = @"C:\Users\musau\Desktop\Murat Yücedağ\C#\52.Ders\resimler\modernsanat.jpg";
            }
            if (comboBox1.Text == "Panorama 1453 Tarih Müzesi")
            {
                richTextBox1.Text = "İsminden de anlaşılacağı gibi İstanbul’un Fethi’ni konu edinen Panorama 1453 Tarih Müzesi, Türkiye’nin ilk panoramik müzesi olmasının yanı sıra dünyanın da üstü kapalı tek panoramik müzesi olma unvanını taşıyor.Müzenin ilk katında İstanbul’un Fethi, ufak detaylarla anlatılıyor.Panoramik fotoğraf ise müzenin kubbe salonunda yer alıyor ve insana, kapalı alanda olmasına rağmen yeniden açık havaya çıkmış hissiyatı yaşatıyor.Yetişkinler kadar çocukların da ilgisini çeken müze, masala açılan bir kapı görevi görüyor. Müzenin Topkapı Kültür Parkı içerisinde yer almasından dolayı da müzeyi gezdikten sonra çocuklar, oyun parklarında doyasıya eğlenebiliyorlar.Panorama 1453 Tarih Müzesi’ne giriş ücretleri, tam bilet 10 TL, indirimli bilet ise 5 TL.Öğrenciler, öğretmenler ve askeri personeller indirimli biletten faydalanabiliyor.Yılın her günü açık olan müzeyi saat 08:00 ile 17:00 arasında ziyaret edebilirsiniz.Zeytinburnu ilçesinde, Merkez Efendi Mahallesi‘nde konumlanan Panorama 1453 Tarih Müzesi’ne gitmek için Kabataş – Bağcılar Tramvay Hattı’nı kullanıp, Tophane Durağı‘nda inebilirsiniz. Ayrıca, metrobüsle Topkapı Durağı’na gelirseniz, birkaç dakika yürüyerek müzeye ulaşabilirsiniz.";
                pictureBox2.ImageLocation = @"C:\Users\musau\Desktop\Murat Yücedağ\C#\52.Ders\resimler\panaroma.jpg";
            }
            if (comboBox1.Text == "Türk ve İslam Eserleri Müzesi")
            {
                richTextBox1.Text = "İlk olarak Evkaf-ı İslamiye Müzesi ismiyle Süleymaniye Külliyesi’nde ziyaretçilerine kapılarını açan müze, Cumhuriyet’in ilan edilmesiyle birlikte Türk ve İslam Eserleri Müzesi olarak anılmaya başlanmış.Cumhuriyet’in ilanıyla birlikte ismi değişse de, müzenin bugün konumlandığı yer olan İbrahim Paşa Sarayı‘nda ziyaretçiler ancak 1983’ten sonra ağırlanabilmiş.Türk ve İslam Eserleri Müzesi içerisinde Türklerin tarih boyunca yaşayışlarına ve kültürlerine ışık tutan metal ve tekstil işleri, savaş silahları, halı dokumaları gibi pek çok eser yer alıyor. Aynı zamanda, İslam Dünyası’na ait el yazmaları örnekleri de müzede sergileniyor.Topkapı Sarayı ve Ayasofya Camii gibi yerlerin sürekli göz önünde bulunmasından dolayı biraz gölgede kalan Türk ve İslam Eserleri Müzesi, İstanbul’da gezilip görülmesi gereken yerlerin başında geliyor.MüzeKart’ın geçerli olduğu müzeye kartsız giriş için 60 TL ücret ödemeniz gerekiyor.Yazın(15 Nisan – 2 Ekim) saat 09:00 ile 19:00 arasında ziyaretçilere kapılarını açan müzeye kışın(3 Ekim – 14 Nisan) ise saat 09:00 ile 17:00 arasında girilebiliyor.Sultanahmet Meydanı‘nda, Sultanahmet Camii’nin karşısında konumlanan İbrahim Paşa Sarayı’nın içerisinde konumlanan Türk ve İslam Eserleri Müzesi’ne gitmek için Bağcılar – Kabataş Tramvay Hattı’nı kullanarak Sultanahmet Durağı‘na gelebilir, buradan da yürüyerek müzeye ulaşabilirsiniz.Anadolu yakasından gelecekler ise, Eminönü, Karaköy veya Kabataş’a vapurla gelerek tramvaya aktarma yapabilecekleri gibi, Marmaray ile Sirkeci‘ye kadar gelerek yine tramvaya binip müzeye ulaşabilirler.";
                pictureBox2.ImageLocation = @"C:\Users\musau\Desktop\Murat Yücedağ\C#\52.Ders\resimler\turk.jpg";
            }
            if (comboBox1.Text == "İstanbul Deniz Müzesi")
            {
                richTextBox1.Text = "Deniz Kuvvetleri Komutanlığı‘na bağlı olan İstanbul Deniz Müzesi, ilk olarak 1897‘de Kasımpaşa’da yer alan ufak bir binada açılmış.II.Dünya Savaşı sırasında eserlerin daha iyi korunabilmesi adına Anadolu’ya gönderilen eserler, savaş sonrasında tekrardan İstanbul’a getiriliyor.Günümüzde bulunduğu yere ise 1961 senesinde taşınmış.Türkiye’nin ilk ve en büyük deniz müzesi olma unvanını elinde bulunduran İstanbul Deniz Müzesi içerisinde 20 bini aşkın eser yer alıyor.4 ana galeri, çocuk odaları, sinevizyon odası, çok amaçlı salon, 2 fuaye ve 2 farklı sanat galerisinin yer aldığı müzede dünyanın en eski kadırgaları ve saltanat kayıkları büyük ilgi görüyor.Yetişkinler için bilet ücreti 13 TL olan müzeye öğrenciler ise ücretsiz olarak girebiliyor.Pazartesi günleri, yılbaşı ve dini bayramlarda ziyarete kapalı olan İstanbul Deniz Müzesi’ni hafta içi saat 09:00 - 17:00 arasında, hafta sonu ise 10:00 – 18:00 arasında ziyaret edebilirsiniz.Beşiktaş ilçesinde, Başbakanlık Ofisi ile Shangri - La Oteli‘nin hemen yanında konumlanan İstanbul Deniz Müzesi’ne gelmek için Bağcılar – Kabataş Tramvay Hattı‘nı kullanabilirsiniz. Kabataş’a geldikten sonra 15 – 20 dakikalık yürüme mesafesinde kalan müzeye dilerseniz Beşiktaş istikametinde giden otobüslerle de ulaşabilirsiniz.Metrobüs ile yolculuk yapacaklar, Zincirlikuyu Durağı’nda inerek, Beşiktaş yönünde hareket eden herhangi bir otobüs veya minibüse binebilirler.Anadolu yakasından gelecekler ise Kadıköy ya da Üsküdar’dan vapura binerek Beşiktaş’a seyahat edebilirler.";
                pictureBox2.ImageLocation = @"C:\Users\musau\Desktop\Murat Yücedağ\C#\52.Ders\resimler\deniz.jpg";
            }
            if (comboBox1.Text == "İstanbul Fethiye Müzesi: Pammakaristos Manastırı")
            {
                richTextBox1.Text = "1292 senesinde inşa edilen yapı, günümüze kadar gelmeyi başarmış.İlk yapılan büyük kuzey kilisesi, Meryem Ana‘ya adanmış. Daha sonra, Mikhail Palagiogos’un eşi Maria, büyük kiliseyi yaptırırken, kuzey kilisesinin yanına ufak bir kilise daha inşa ettirmiş.Bu ek kilisede, Maria ve Mikhail’in mezarları da yer alıyor.Fatih Sultan Mehmet’in İstanbul’u fethetmesiyle kilise, kadınlar manastırına dönüştürülmüş.Daha sonra Hristiyanların elinde kaldığı için 1586’da Havarium Kilisesi‘nden çıkan patrikhane buraya taşınmış.III.Murad, Azerbaycan ve Gürcistan seferlerinin anısına kiliseye minare ve mihrap eklettirmiş ve adını da Fethiye koymuş.Tüm eski kiliseler gibi günümüzde müze olarak kullanılan yapının camii bölümü ise hala ibadete açıktır.Ancak, tarihi dokusu zarar görmesin diye camii, ezandan 20 dakika önce açılır ve namazdan hemen sonra kapatılır.1938’de restore edilen yapı, Ayasofya Camisi’ne eklenmiş.İstanbul Fethiye Müzesi içerisinde yer alan mozaiklerin bir kısmı zarar görmüş olsa da halen göz alıcı güzelliklerini koruyorlar.Son dönem Bizans mimarisinin esintilerinin görüldüğü yapının kubbesi ve duvarları, 14.yüzyıldan kalma mozaiklerle döşenmiş.Eskiden kilise olarak kullanıldığı için Hristiyan dini motiflerinin sıklıkla görüldüğü müzenin sunak bölümünde Hz. İsa, Meryem Ana ve Vaftizci Yahya’nın tasvir edildiği ihtişamlı bir deisis yer alıyor.Yazın(15 Nisan – 2 Ekim) saat 09:00 ile 19:00 saatlerinde ziyarete açık olan müzeye kışın(3 Ekim – 14 Nisan) ise saat 09:00 ile 17:00 arasında gelebilirsiniz.Müzeye giriş ücreti ise 10 TL‘dir.Oldukça merkezi bir konumda yer almasından dolayı İstanbul Fethiye Müzesi’ne, üzerinde Fatih yazan neredeyse her otobüsle gidebilirsiniz.";
                pictureBox2.ImageLocation = @"C:\Users\musau\Desktop\Murat Yücedağ\C#\52.Ders\resimler\fethiye.jpg";
            }
            if (comboBox1.Text == "Galata Mevlevihanesi Müzesi")
            {
                richTextBox1.Text = "1491 senesinde Afyon Mevlevihanesi Şeyhi Divane Mehmed Dede tarafından inşa ettirilen Galata Mevlevihanesi, İstanbul’un ilk mevlevihanesi olma unvanını taşıyor.1509 yılında yaşanan Büyük İstanbul Depremi ve ardından çıkan birkaç yangın, mevlevihaneye oldukça zarar vermiş.Günümüzdeki görünümüne ise büyük ölçüde 1851 – 1859 arasında yapılan restorasyon çalışmalarıyla kazanmış.Cumhuriyet’in ilan edilmesiyle birlikte mektep olarak hizmet veren Galata Mevlevihanesi, 1975’te Divan Edebiyatı Müzesi’ne dönüştürülmüş.İçerisinde; Şeyh Galip ve Halet Efendi Türbeleri, Semahane, Mahfiller, Derviş Odaları, semahlarda kullanılan enstrümanlar ile pek çok sanat eserinin yer aldığı Galata Mevlevihanesi Müzesi, 2007 ile 2011 yılların arasında yapılan yenileme çalışmaları sayesinde bugünkü görünümüne kavuşmuş.Pazartesi günleri ile Ramazan ve Kurban bayramlarının ilk günleri dışında daima açık olan Galata Mevlevihanesi Müzesi’ni kışın(1 Kasım – 15 Nisan) saat 09:00 ile 16:30 arasında, yazın(15 Nisan – 1 Kasım) ise 09:00 ile 19:00 arasında ziyaret edebilirsiniz.Müzeye giriş ücreti 25 TL iken, 18 yaşında altındaki ve 65 yaşın üstündeki T.C.vatandaşlarından, gazilerden, gazi ve şehir yakınlarından, engellilerden ve refakatçilerinden, er ve erbaşlardan, 12 yaşın altındaki yabancı uyruklu çocuklardan, basın kartına sahip kişilerden ve bakanlık onaylı tur rehberlerinden ücret alınmıyor.MüzeKart’ın geçerli olduğu Galata Mevlevihanesi Müzesi’nde her Pazar saat 17:00’de sema gösterisi düzenleniyor. Bu gösteriyi izlemek içinse ekstra ücret ödemeniz gerekiyor ve MüzeKart geçerliliğini yitiriyor.İstiklal Caddesi’nin sonunda, Galipdere Caddesi’nin hemen başında konumlanan Galata Mevlevihanesi Müzesi’ne gitmek için kullanabileceğiniz birçok ulaşım aracı bulunuyor.Taksim Meydanı’ndan yürüyerek ya da metroya binip Şişhane’ye giderek müzeye ulaşabilirsiniz. Karaköy’den de 10 dakika kadar yürüyebilir veya Tünel’e giden fünikülere binebilirsiniz.";
                pictureBox2.ImageLocation = @"C:\Users\musau\Desktop\Murat Yücedağ\C#\52.Ders\resimler\galata.jpg";
            }
            if (comboBox1.Text == "Jale Kuşhan Balmumu Heykel Müzesi")
            {
                richTextBox1.Text = "Dünyanın ilk 4 boyutlu heykel müzesi olma özelliği taşıyan Jale Kuşhan Balmumu Heykel Müzesi’ne yapacağınız ziyarette, 40 dakika boyunca ziyaretçilere bilgi aktarılıyor ve bu aktarım sinevizyon gösterimleri ile destekleniyor.Müzenin dikkat çekici özelliklerinden bir tanesi de bazı balmumu heykellere hareket özelliği kazandırılmış olması.Müzede, başta Mustafa Kemal Atatürk olmak üzere Kanuni Sultan Süleyman, Osmangazi, Yavuz Sultan Selim ve Fatih Sultan Mehmet, Fuzuli, Leonardo Da Vinci, Rumi, Nazım Hikmet, İbn-i Sina, Mevlana Celaleddin-i Rumi, Yunus Emre ve Mimar Sinan, Elvis Presley, Arnold Schwarzenegger, Michael Jackson, Mihail Gorbaçov, Alparslan, Hürrem Sultan, Timur ve Fransa Kralı XV. Lois gibi pek çok ünlü ismin balmumu heykeli ziyaretçileri karşılıyor.Üstelik, heykelleri bulunan kişilerin kemik ölçüleri alındığı için ölçüler birebir uyuyor.Haftanın her günü kapılarını ziyaretçilere açan Jale Kuşhan Balmumu Heykel Müzesi giriş ücretleri ise; tam bilet 30 TL, indirimli bilet ise 20 TL.Ayrıca, 7 yaşın altındaki çocuklar, basın mensupları, engelliler ve refakatçileri müzeye ücretsiz girebiliyorlar.Şişli ilçesinde, Cevahir AVM içerisinde konumlanan müzeye metrobüs, metro ve otobüsle ulaşım sağlayabilirsiniz.";
                pictureBox2.ImageLocation = @"C:\Users\musau\Desktop\Murat Yücedağ\C#\52.Ders\resimler\jale.jpg";
            }
            if (comboBox1.Text == "Harbiye Askeri Müzesi")
            {
                richTextBox1.Text = "15. yüzyıla dayanan tarihiyle Harbiye Askeri Müzesi, İstanbul’un gezilmesi gereken yerleri arasında üst sıralarda bulunuyor.Zaman içerisinde müzede eser sayısının artması sebebiyle bazıları Çinili Köşk‘e taşınmış. Bu vesileyle de İstanbul Arkeoloji Müzesi‘nin temelleri atılmış.Müzenin en dikkat çekici özelliklerinden bir tanesi de sinemasının, mehterinin, kütüphanesinin ve yayınlarının zamanın çağdaş müzecilik anlayışına uygun bir müze olması.1940 senesine kadar Aya İrine‘de bulunan Harbiye Askeri Müzesi, II.Dünya Savaşı sırasında bir dönem kapatılmış. Savaşın bitmesiyle de yeniden hizmete açılmış.1966’da binanın koleksiyonlarının yetersiz olduğu düşüncesiyle yenileme çalışmalarına başlanmış ve ancak 1993 yılında ziyarete açılabilmiş.Pazartesi ve salı günleri, dini bayramların ilk günü ve yılbaşında kapalı olan Harbiye Askeri Müzesi’ne saat 09:00 ile 16:30 arasında gidebilirsiniz. Ayrıca müzede, saat 15:00 ile 16:00 arasında mehteran takımı gösterisi gerçekleştiriliyor.Müzeye giriş ücretleri ise tam 6 TL, öğrenciler için ise ücretsizdir. Şişli ilçesinde, Mecidiyeköy Mahallesi, Valikonağı Caddesi üzerinde konumlanan Harbiye Askeri Müzesi’ne gitmek için metro, tramvay, füniküler, IDO ve otobüs kullanabilirsiniz.Toplu taşıma araçlarına göre müzeye en yakın inebileceğiniz duraklar ise şu şekilde; tramvayla seyahat edecekler için Fındıklı Tramvay Durağı, fünikülerle seyahat edecekler için Taksim Füniküler Durağı, metroyla seyahat edecekler için Şişli Metro İstasyonu, İDO ile seyahat edecekler için Kabataş İDO Vapur İstasyonu, otobüsle seyahat edecekler içinse Harbiye Otobüs Durağı‘dır.";
                pictureBox2.ImageLocation = @"C:\Users\musau\Desktop\Murat Yücedağ\C#\52.Ders\resimler\harbiye.jpg";
            }
            if (comboBox1.Text == "Rahmi Koç Müzesi")
            {
                richTextBox1.Text = "Tarihi Lengerhane binası, tarihi Hasköy tersanesi ve Açık hava sergileme alanı olmak üzere üç ana bölümden oluşan Rahmi Koç Müzesi, Rahmi Koç’un desteğiyle 1994 senesinde hizmete açılmış.Lenger, gemileri sabitlemek için denize atılan zincir ve çapa anlamına geliyor. Lengerhane de bu malzemeleri yapıldığı yer, imalathane olarak biliniyor.Lengerhane binası, 1991’de Rahmi Koç tarafından satın alınarak müzeye dönüştürülmüş. Hasköy tersanesi de Lengerhane’nin hemen karşısında konumlanıyor.2001’e kadar devam eden yenileme çalışmalarının ardından Rahmi Koç Müzesi bünyesine eklenmiş.Tersane, 1861’de Şirket-i Hayriye tarafından, kendi gemilerinin bakım ve onarım işlerinin halledilmesi amacıyla kurulmuş.Açık hava sergileme alanı ise Hasköy Caddesi’nde konumlanıyor ve ana girişten Haliç’e kadar uzanıyor.Klasik otomobiller, Libertorlar, uçaklar ve kocaman boyutlardaki Turgut Alp Vinci’ne kadar pek çok eser açık hava sergileme alanında yer alıyor.Rahmi Koç Müzesi, kış döneminde(1 Ekim – 31 Mart) Cumartesi, Pazar ve bayram günleri saat 10:00 – 18 arasında ziyarete açıkken, yaz döneminde(1 Nisan – 30 Eylül) ise yine aynı günlerde saat 10:00 – 18:00 arasında kapılarını açıyor.Ayrıca, Salı ve Cuma günleri de saat 10:00 – 17:00 arasında ziyaret edilebiliyor.MüzeKart sahiplerine bilet fiyatında % 20 indirim imkanı sunan müzeye giriş ücretleri ise; tam bilet 28 TL, öğrenci bileti 12 TL, denizaltı yetişkin bileti 14 TL, denizaltı öğrenci bileti 10 TL.Hasköy‘de konumlanan Rahmi Koç Müzesi’ne belediye otobüsleri, Şişhane – Alibeyköy hattında çalışan minibüsler, şehir atları, Üsküdar – Eyüp hattında çalışan vapurlar ve Halıcıoğlu Metrobüs Durağı’ndan hareket eden metrobüsler ile ulaşım sağlamak mümkün.";
                pictureBox2.ImageLocation = @"C:\Users\musau\Desktop\Murat Yücedağ\C#\52.Ders\resimler\rahmi.jpg";
            }
            if (comboBox1.Text == "Pera Müzesi")
            {
                richTextBox1.Text = "Pera Müzesi, tasarımı Mimar Achille Manoussos tarafından yapılan Bristol Oteli binasının cephesi korunarak 2005 senesinde hizmet vermeye başlamış.Müzenin kuruluş amacı, Suna ve İnan Kıraç Vakfı’na ait olan “Oryantalist Resim”, “Anadolu Ağırlık ve Ölçüleri” ve “Kütahya Çini ve Seramikleri” koleksiyonlarını sergilemek ve düzenlenen etkilerle kamuyla paylaşmak.Şehrin en hareketli bölgesinde konumlanan müze, çağdaş müzecilik anlayışıyla faaliyet gösteriyor. İçerisinde 300’den fazla eserin bulunduğu Oryantalist Resim Koleksiyonu, Pera Müzesi’nde sergileniyor.Bu koleksiyonda, 17.ve 19.yüzyıl Avrupa oryantalistlerinin eserleri yer alıyor.Bu oryantalistlerin en büyük özelliği ise eserlerini, Osmanlı kültüründen etkilenerek ortaya çıkarmış olmaları.Müzede, ‘Pera Film’ adı altında her ay düzenlenen tematik film etkinliklerine katılabileceğiniz gibi, ‘Pera Eğitim’ adıyla çocuk ve gençlerin faydalandığı eğitimlere katılabilirsiniz.Pazartesi günleri kapalı olan Pera Müzesi’ne salı ve cumartesi günleri saat 10:00 ile 19:00 arasında, pazar günleri de saat 12:00 ile 18:00 arasında gidebilirsiniz. Ayrıca müze, ‘Uzun Cuma’ adı altında her Cuma saat 18:00 – 22:00 arasında ücretsiz olarak kapılarını ziyaretçilere açıyor.Pera Müzesi’ne giriş ücretleri ise; tam bilet 25 TL, grup bileti 20 TL ve öğrenci bileti de 10 TL olarak belirlenmiş.Pera Müzesi Dostları, Genç Çarşamba(öğrenciler), engelliler ve refakatçileri, 12 yaşın altındaki çocuklar, ICOM kart sahipleri ve basın kartı sahipleri müzeden ücretsiz şekilde yararlanabiliyorlar.Tepebaşı semtinde, TRT binasının arkasında konumlanan Pera Müzesi’ne gitmek için ilk olarak Taksim’e giden otobüslere binip, Tepebaşı Durağı’nda inmeniz gerekiyor.Ardından, Meşrutiyet Caddesi üzerinde ilerlediğiniz takdirde sol tarafınızda Pera Müzesi’ni göreceksiniz.";
                pictureBox2.ImageLocation = @"C:\Users\musau\Desktop\Murat Yücedağ\C#\52.Ders\resimler\pera.jpg";
            }
            if (comboBox1.Text == "Yeşilköy Havacılık Müzesi")
            {
                richTextBox1.Text = "I. Dünya Savaşı sonunda elde edilen ganimetlerle birlikte düşman milletlere ait uçaklar, müze kurma fikrini ortaya çıkarmış.Kurtuluş Savaşı sırasında zarar göreceği düşünülen bu parçalar Maltepe’ye taşınmaya başlamış fakat, nakliye sırasında uçaklar zarar görmüş ve müze kurma fikri rafa kaldırılmış.1960 yılına gelindiğinde Hava Kuvvetleri Komutanı Hv. Org.İrfan Tansel, bir havacılık müzesi kurulması emrini vermiş ve yapılan çalışmalar sonucunda müze 1971 yılında İzmir’de faaliyete başlamış.Fakat müzeye yeterince ilgi gösterilmediği için 1985 senesinde günümüzdeki yerine taşınmış.3 bin metrekare kapalı, 12 bin metrekare açık, toplamda 15 bin metrekare alan üzerine kurulu olan Yeşilköy Havacılık Müzesi’nde, Türk Hava Kuvvetleri’nin geçmişten günümüze dek kullandığı hava araçları, maket koleksiyonları, havacılıkta kullanılan araç ve gereçler, havacı şehitlerimizin elbiseleri, havacılığın dünden bugüne olan serüveni konulu eserler ve silahlar gibi pek çok eser yer alıyor.Buna ek olarak, müzeyi gezdikten sonra içeride bulunan kafeteryada kahvenizi yudumlayarak biraz soluklanabilir, oldukça uygun fiyatlarla müzede konumlanan mağazadan maket uçak satın alabilirsiniz.Pazartesi günleri dışında her gün açık olan Yeşilköy Havacılık Müzesi’ne hafta içi saat 09:00 ile 17:00 arasında, hafta sonu ise saat 10:00 ile 18:00 arasında gidebilirsiniz.Yetişkinler için 13 TL olan giriş ücreti öğrencilerden alınmamaktadır.Yeşilköy’de Hava Harp Okulu Destek Bölüğü’nün, askeri havalimanının yanında konumlanan Yeşilköy Havacılık Müzesi’ne gitmek için, Sirkeci - Halkalı Banliyö Treni’ni kullanabilirsiniz. Trenle Yeşilköy Durağı‘na gelerek 5 – 10 dakika yürüdüğünüz takdirde müzeye ulaşabilirsiniz.";
                pictureBox2.ImageLocation = @"C:\Users\musau\Desktop\Murat Yücedağ\C#\52.Ders\resimler\havaci.jpg";
            }
            if (comboBox1.Text == "Türkiye İş Bankası Müzesi")
            {
                richTextBox1.Text = "Fotoğraflar, belgeler, belgeseller ve hatıralar 83 sene boyunca toplanmış ve Türkiye İş Bankası Müzesi’nde sergilenmeye başlanmış.Müze, 1890‘da inşa edilen Postane Binası‘nda yer alıyor.Adı Postane Binası olsa da, Sirkeci‘de bulunan büyük postane binasının yapımının tamamlanması ve kullanıma açılmasından dolayı bina, uzun yıllar postane olarak kullanıma açılmadı.Yapı, 1917 yılında kurulan Osmanlı İtibar-ı Milli Bankası‘na devredildi. 1927’de ise İş Bankası, Osmanlı İtibar - ı Milli Bankası ile birleşti. Böylece bina, İş Bankası bünyesine geçmiş oldu.2004’e kadar Türkiye İş Bankası’nın bir şubesi olarak hizmet veren binanın aynı yıl içerisinde iki üst katı kaldırıldı ve 2005’te de müze olarak hizmet vermesi için çalışmalara başlandı.Eski eşyalar, duvarlar ve işlemeler korunurken, en alt katta yer alan kasalar da sergilenmeye açık hale getirildi.Üst katları sergi alanı olarak tasarlanan binada, geçmiş dönemlerde Atatürk, Çanakkale Savaşı, Cumhuriyet’in ilk yılları, bankacılık tarihi ile ilgili sergiler organize edilmiş ve devam eden süreçte de düzenlenmesi planlanıyor.Eminönü’nde, Bankacılar Caddesi üzerinde konumlanan Türkiye İş Bankası Müzesi’ne girişler ücretsiz.Pazartesi günleri, dini bayramların ilk günü ve 1 Ocak’ta ziyarete kapalı olan müzeyi diğer günlerde saat 10:00 ile 18:00 arasında ziyaret edebilirsiniz.Oldukça merkezi bir konumda yer almasından dolayı da hem tramvay hem de otobüsle rahatça ulaşım sağlayabilirsiniz.";
                pictureBox2.ImageLocation = @"C:\Users\musau\Desktop\Murat Yücedağ\C#\52.Ders\resimler\is.jpg";
            }
            if (comboBox1.Text == "Büyük Postane (PTT Müzesi)")
            {
                richTextBox1.Text = "1905‘te yapımına başlanan ve 1909’da tamamlanan Büyük Postane (PTT Müzesi), Türkiye’nin en büyük postane binası olma unvanını taşıyor.Posta ve Telgraf Nezareti Binası olarak hizmet vermesi amacıyla inşa edilen bina ilkin Posta ve Telgraf Nezareti Binası olarak adlandırılsa da 1930’da Yeni Postane, birkaç yıl sonra da Büyük Postane adıyla anılmaya başlanmış.Mimar Vedat Tek tarafından tasarlanan yapı, 3 bin 200 metrekarelik alan üzerine kurulu 4 katlı bir binadan meydana geliyor.Osmanlı klasik mimarisi ile çini işlemeciliği ön plana çıkan yapı, zamanında İstanbul Radyo Evi olarak da faaliyet göstermiş.1958’de ise tam anlamıyla postane olarak hizmet vermeye başlamış.Günümüzde ise halen, aktif olarak PTT Başmüdürlüğü olarak faaliyet gösteriyor.Fatih ilçesinde, Sirkeci‘de konumlanan Büyük Postane’ye hafta içi her gün saat 09:00 – 17:00 arasında gidebilirsiniz.Hafta sonu hizmete kapalı olan postaneye girişler ise ücretsiz.Büyük Postane’ye gitmek için birçok ulaşım aracını tercih edebilirsiniz. Bu ulaşım araçlarından; tren ile Sirkeci Tren İstasyonu’na, tramvay ile Sirkeci Tramvay Durağı’na, arabalı vapur ile Sirkeci İDO Arabalı Vapur İstasyonu’na, otobüsle ise Eminönü İskele Otobüs Durağı’na gelerek postaneye ulaşım sağlayabilirsiniz.";
                pictureBox2.ImageLocation = @"C:\Users\musau\Desktop\Murat Yücedağ\C#\52.Ders\resimler\ptt.jpg";
            }
            if (comboBox1.Text == "Pelit Çikolata Müzesi")
            {
                richTextBox1.Text = "İçerisinde çikolatadan bir dünyanın yaratıldığı Pelit Çikolata Müzesi, çikolataseverlerin tam anlamıyla bayılacağı mekanlardan bir tanesi.Pelit tarafından çikolata severler için düzenlenen bu müze, hem çocuklara hem de yetişkinlere hitap ediyor.Müzenin içerisinde çikolatadan inşa edilmiş köyler, ünlü isimlerin heykelleri, çikolata çeşmeleri gibi pek çok yapı bulunuyor. Bu yapıların en önemli özelliği de sadece çikolatadan yapılmış olmaları.İmalat alanının üzerinde konumlanan cam bir tüpün içerisine girerek tüm imalat sürecine tanıklık edebildiğiniz gibi Pelit’e ait bazı eski üretim malzemelerini de inceleyebiliyorsunuz.Bu çikolata dünyasının içinde ayrıca, çocukların pastacılığı öğrenmeleri ya da en azından fikir edinmeleri için kurulmuş bir mini mutfak yer alıyor. Burada çocuklara, pasta yapımı ile ilgili eğitim ve workshoplar veriliyor.5 yaşın altındaki çocukların ücretsiz girebildiği Pelit Çikolata Müzesi’ne giriş ücreti, diğer herkes için kişi başı 50 TL.Ayrıca, haftanın her günü saat 10:00 – 17:00 arasında kapılarını ziyaretçilerine açıyor.Esenyurt ilçesinde konumlanan ve 25 bin metrekarelik alan üzerine inşa edilmiş Pelit Çikolata Müzesi’ne, Esenyurt istikametinde hareket eden otobüslere binerek ulaşabilirsiniz.";
                pictureBox2.ImageLocation = @"C:\Users\musau\Desktop\Murat Yücedağ\C#\52.Ders\resimler\pelit.jpg";
            }
            if (comboBox1.Text == "İstanbul Arkeoloji Müzesi")
            {
                richTextBox1.Text = "İstanbul müzelerinin en ihtişamlılarından bir tanesi de İstanbul Arkeoloji Müzesi. Fatih Sultan Mehmet’e kadar uzanan tarihi ve içerisinde yer alan tarihi eserleriyle İstanbul Arkeoloji Müzesi, yaşadığımız coğrafyanın tarihine, kültürüne, mimarisine ve yaşayış biçimine ışık tutuyor.Dünyanın sayılı müzeleri arasında gösterilen İstanbul Arkeoloji Müzesi’nin bu klasmanda sayılmasını sağlayansa, 1881’de müze müdürlüğüne atanan Sadrazam Edhem Paşa’nın oğlu Osman Hamdi Bey‘dir.Müzeyi topluma kazandıran Osman Hamdi Bey, aynı zamanda arkeolojik kazılara bizzat katılarak müzeyi daha da zenginleştirir.On binlerce yıl öncesinden kalma eserlerin dahi sergilendiği müze, tüm dünyayı kıskandıracak nitelikte eserler barındırıyor.Arkeoloji Müzesi, Eski Şark Eserleri Müzesi ve Çinili Köşk Müzesi olmak üzere 3 ayrı birimden oluşan İstanbul Arkeoloji Müzeleri içerisinde İskender Lahdi, Tabnit Lahdi, Çiviyazılı Belgeler Arşivi, Gezer Takvimi, Siloa Yazıtı ve Vize Tümülüsü gibisi dünyada eşi bulunmayan, çok nadide eserlere ev sahipliği yapıyor.Dünyanın en eski tarihi miraslarından bir tanesine sahip olan müzede 1 milyona yakın eser sergileniyor.Pazartesi günleri hariç her gün ziyarete açık olan müzeye yazın(15 Nisan – 2 Ekim) saat 09:00 – 19:00 arasında, kışın(3 Ekim – 14 Nisan) ise saat 09:00 – 17:00 arasında gidebilirsiniz.MüzeKart’ın geçerli olduğu İstanbul Arkeoloji Müzesi’ne giriş ücreti 60 TL iken, 18 yaşın altında ve 65 yaşın üstündeki T.C.vatandaşları, 12 yaşın altındaki yabancı uyruklu çocuklar, gaziler, gazi ve şehit yakınları, er ve erbaşlar, engelliler ve refakatçileri, rehberler, rehberlik eden öğretmenler ve basın kimlik kartı olanlar ise müzeye ücretsiz giriş yapabiliyor.Osman Hamdi Bey Yokuşu üzerinde konumlanan İstanbul Arkeoloji Müzesi’ne gitmek için Bağcılar – Kabataş hattında çalışan tramvaya binerek Gülhane Durağı‘nda inebilir, buradan da yürüyerek müzeye ulaşabilirsiniz.Anadolu yakasından gelecekler ise Eminönü veya Kabataş’a kadar vapurla gelip, tramvaya aktarma yapabilirler.İstanbul’un fethinden sonra Fatih Sultan Mehmet tarafından inşa ettirilen Çinili Köşk, bölgede yapılan müsabakaları izlemek için Fatih Sultan Mehmet tarafından yazlık saray olarak kullanılıyormuş.Giriş kapısında yer alan 14 sütunla ziyaretçilerine gösterişli bir “Hoş geldin” diyen yapı, ön taraftan tek kat gibi görünse de arkadan bakıldığında iki kat olduğu anlaşılıyor.Sırça Köşk adıyla da bilinen eserin Çinili Köşk Müzesi adını almasının sebebi ise içerisinde yer alan çini ve seramiklerdir.Aynı zamanda, arkeolojik kazılar sonucunda ele geçirilen 2000’e yakın eser yine Çinili Köşk Müzesi’nde sergileniyor.";
                pictureBox2.ImageLocation = @"C:\Users\musau\Desktop\Murat Yücedağ\C#\52.Ders\resimler\arkeoloji.jpg";
            }
            if (comboBox1.Text == "Madame Tussauds İstanbul Balmumu Heykel Müzesi")
            {
                richTextBox1.Text = "Dünya çapında üne sahip olan müze, ilk olarak bundan tam 250 sene önce, dönemin başarılı balmumu sanatçılarından Dr. Philippe Curtius’un eğitim verdiği Marie tarafından Londra’da açılmış.İngiltere’deki müzenin geniş kitleler tarafından ziyaret edilmesi ve ilgi görmesi sonucu ikili, kraliyet ailesine eğitim vermek adına Fransa’ya geçmiş ve burada birçok sergi açmış.İlk başlarda müzede kraliyet mensuplarının, politikacıların ve devrimcilerin heykelleri bulunsa da, zaman içerisinde sporcuların, bilim insanlarının ve müzisyenlerin de heykelleri müzeye eklenmiş.Böylece Madame Tussauds, milyonlarca kişiye kendisine hayran bırakan bir cazibe merkezi haline dönüşmüş.2016’da kapılarını ziyaretçilerine açan Madame Tussauds İstanbul Balmumu Heykel Müzesi ise Madame Tussauds’un 21.şubesi olarak biliniyor.Heykellerin bu denli ilgi görmesinin en büyük sebebi ise asıllarıyla birebir aynı ölçüleri taşıyor olması.Bunun için, heykeli yapılacak kişinin defalarca ölçüsü alınıp yüzlerce fotoğrafı çekiliyor. Daha sonra, alınan ölçüler ve fotoğraflardan yararlanarak 140 kilogramlık kilden kalıp oluşturuluyor. 6 ayrı işlemden daha geçen heykel, en sonunda 300 bin dolar değerinde bir şahesere çevriliyor.Madame Tussauds İstanbul Balmumu Heykel Müzesi’nde yer alan eserler; müzik, spor, bilim ve kültür, VIP party, tarih ve liderler olmak üzere 5 ayrı kategoriye ayrılıyor.Her bir kategoride, alanının en başarılı isimlerin heykellerini görmek mümkün.Saat 10:00 ile 20:00 arasında ziyarete açık olan müzeye 0 – 3 yaş arası çocuklar ücretsiz giriş yapabiliyor. 14 yaşından küçük çocuklara ise mutlaka bir yetişkinin eşlik etmesi gerekiyor.Müzeye giriş için tek kullanımlık ve VIP olmak üzere 2 ayrı kategoride bilet satılıyor. Tek kullanımlık biletler, 14 yaşın üzerindeki kişiler için 109 TL, öğrenciler ver 3 – 14 yaş arasındaki çocuklar içinse 69 TL‘den satılıyor. Biletinizi internetten satın alırsanız % 40 indirimli fiyatlardan yararlanabiliyorsunuz.Madame Tussauds İstanbul biletleri için müzenin sitesini mutlaka kontrol etmelisiniz.13 yaş üzeri kişilerin yararlanabildiği VIP biletin fiyatı ise 103 TL.Bu biletin ziyaretçilere sağladığı avantajlar ise: hediyelik eşya mağazasından indirim hakkı, rehber kitapçık, fotoğraf ve balmumu el figürü hediyesi, sıra beklemeden müzeye giriş hakkı ve SEA LIFE İstanbul’a da giriş hakkı sunuyor. 127 TL’ye ise Legoland’e de giriş yapabilirsiniz.İstiklal Caddesi üzerinde, Grand Pera Alışveriş Merkezi‘nde konumlanan Madame Tussauds İstanbul Balmumu Heykel Müzesi’ne gitmek için otobüs, minibüs, metro, vapur ve füniküler kullanabilirsiniz.";
                pictureBox2.ImageLocation = @"C:\Users\musau\Desktop\Murat Yücedağ\C#\52.Ders\resimler\madam.jpg";
            }
            if (comboBox1.Text == "Topkapı Sarayı Müzesi")
            {
                richTextBox1.Text = "Topkapı Sarayı (Osmanlı Türkçesi: طوپقپو سرايى), İstanbul Sarayburnu'nda, Osmanlı İmparatorluğu'nun 600 yıllık tarihinin 400 yılı boyunca, devletin idare merkezi olarak kullanılan ve Osmanlı padişahlarının yaşadığı saraydır.[1] Bir zamanlar içinde 4.000'e yakın insan yaşamıştır.[2]Topkapı Sarayı Fatih Sultan Mehmed tarafından 1478’de yaptırılmış, Abdülmecid’in Dolmabahçe Sarayı’nı yaptırmasına kadar yaklaşık 380 sene boyunca devletin idare merkezi ve Osmanlı padişahlarının resmi ikâmetgâhı olmuştur.Kuruluş yıllarında yaklaşık 700.000 m²'lik bir alanda yer alan sarayın bugünkü alanı 80.000 m²'dir.[3]Topkapı Sarayı, saray halkının Dolmabahçe Sarayı, Yıldız Sarayı ve diğer saraylarda yaşamaya başlaması ile birlikte boşaltılmıştır. Padişahlar tarafından terk edildikten sonra da içinde birçok görevlinin yaşadığı Topkapı Sarayı hiçbir zaman önemini kaybetmemiştir. Saray zaman zaman onarılmıştır. Ramazan ayı içerisinde padişah ve ailesi tarafından ziyaret edilen Kutsal Emanetler'in bulunduğu Hırka-i Saadet Dairesi’nin her yıl bakımının yapılmasına ayrı bir önem verilmiştir.[3]Fatih Sultan Mehmed 1465 yılında Topkapı Sarayı'nın inşaatını başlatmıştır.Topkapı Sarayı’nın ilk defa, adeta bir müze gibi ziyarete açılması Abdülmecid dönemine rastlamıştır.O dönemin İngiliz elçisine Topkapı Sarayı Hazinesi’ndeki eşyalar gösterilmiştir.Bundan sonra Topkapı Sarayı Hazinesi’ndeki eski eserleri yabancılara göstermek gelenek haline gelir ve Abdülaziz zamanında, ampir üslupta camekanlı vitrinler yaptırılır, hazinedeki eski eserler bu vitrinler içinde yabancılara gösterilmeye başlanır.II.Abdülhamid tahttan indirildiği sıralarda Topkapı Sarayı Hazine - i Hümâyûn’un pazar ve salı günleri olmak üzere halkın ziyaretine açılması düşünülmüşse de bu gerçekleşememiştir.Mustafa Kemal Atatürk’ün emriyle 3 Nisan 1924 tarihinde halkın ziyaretine açılmak üzere İstanbul Âsâr - ı Atika Müzeleri Müdürlüğü’ne bağlanan Topkapı Sarayı önce Hazine Kethüdalığı, sonra Hazine Müdüriyeti adıyla hizmet vermeye başlamıştır.Bugün ise Topkapı Sarayı Müzesi Müdürlüğü adıyla hizmet vermeye devam etmektedir.1924 yılında bazı ufak onarımlar yapıldıktan ve ziyaretçilerin gezebilmeleri için gereken idari önlemler de alındıktan sonra Topkapı Sarayı 9 Ekim 1924 tarihinde müze olarak ziyarete açılmıştır.O tarihte ziyarete açılan bölümler Kubbealtı, Arz Odası, Mecidiye Köşkü, Hekimbaşı Odası, Mustafa Paşa Köşkü ve Bağdat Köşkü’dür.[3]Günümüzde büyük turist kitlelerini kendine çeken saray 1985 yılında UNESCO Dünya Mirasları Listesi'ne giren İstanbul Tarihî yarımada içerisindeki tarihi eserlerin en başında gelmektedir.[4] Günümüzde müze olarak hizmet vermektedir.[5]";
                pictureBox2.ImageLocation = @"C:\Users\musau\Desktop\Murat Yücedağ\C#\52.Ders\resimler\topkapi.jpg";
            }
            if (comboBox1.Text == "Dolmabahçe Sarayı")
            {
                richTextBox1.Text = "Dolmabahçe Sarayı, İstanbul, Beşiktaş'ta, Kabataş'tan Beşiktaş'a uzanan Dolmabahçe Caddesi'yle İstanbul Boğazı arasında, 250.000 m²lik bir alan üzerinde bulunan Osmanlı sarayı. Marmara Denizi'nden Boğaziçi'ne deniz yoluyla girişte sol kıyıda, Üsküdar ve Kuzguncuk'ın karşısında yer alır. İnşaatı 1843 yılında başlayıp 1856 yılında bitmiştir.";
                pictureBox2.ImageLocation = @"C:\Users\musau\Desktop\Murat Yücedağ\C#\52.Ders\resimler\dolmabahce.jpg";
            }
        }
    }
    }
